### ISSUE TITLE
Exercises - in Case: Word Play 

### ISSUE THREAD

**Issue by lzblack** [brandonchin00/OIM3640#10]
Find out all the words that only use the letters from "planet": https://github.com/brandonchin00/OIM3640/blob/16d10b5262f2df84baad81637320017044e873bf/session11/word.py#L135-L139

**Comment by brandonchin00** [comment]
<img width="552" alt="Screenshot 2021-12-10 012020" src="https://user-images.githubusercontent.com/89877759/145526974-33b3e747-7dee-4c0f-89b3-32d8b5ac33c6.png">
