### ISSUE TITLE
analyze_book.py

### ISSUE THREAD

**Issue by lzblack** [brandonchin00/OIM3640#12]
The hint is in docstring:
https://github.com/brandonchin00/OIM3640/blob/c0a264d9bcecfa0703e4f6119ea04361a4ae500b/session15/textanalysis.py#L76-L83

**Comment by brandonchin00** [comment]
<img width="718" alt="Screenshot 2021-12-10 032819" src="https://user-images.githubusercontent.com/89877759/145542255-fce5eec9-3dd7-4036-884b-2190be5b612f.png">

**Comment by brandonchin00** [comment]
I fixed the code
