### ISSUE TITLE
Exercise in Session 05

### ISSUE THREAD

**Issue by lzblack** [brandonchin00/OIM3640#4]
https://github.com/brandonchin00/OIM3640/blob/7010d6c8dc549e65c32abe66ccd9e3de925b0286/session05/my_abs.py#L7-L14

You cannot define a function this way.

No indentations allowed before `def`

**Comment by brandonchin00** [comment]
<img width="770" alt="Screenshot 2021-12-10 021347" src="https://user-images.githubusercontent.com/89877759/145532799-99449b70-8125-4fd7-8903-a6ec0d7e0816.png">

**Comment by brandonchin00** [comment]
I fixed it and simplified it
