### ISSUE TITLE
Missing Exercises in Strings

### ISSUE THREAD

**Issue by lzblack** [brandonchin00/OIM3640#9]

**Comment by brandonchin00** [comment]
<img width="851" alt="Screenshot 2021-12-10 012751" src="https://user-images.githubusercontent.com/89877759/145527905-2b4e7662-c4a5-4068-b530-c1a0e163165e.png">

**Comment by brandonchin00** [comment]
I did the exercises, but I labelled it under session 10 instead of session 9 and they were in different files under session 10.
